[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  included_files = [
    "app.js",
    "styles.css",
    "assets/**",
    "content/**"
  ]
